from __future__ import annotations

from typing import Protocol

from book_loop.domain.models import Character, CharacterRelation


class CharacterRepository(Protocol):
    """Application port for character persistence."""

    def save_character(self, character: Character) -> None: ...
    def get_character(self, character_id: str) -> Character: ...
    def list_characters(self, *, book_id: str) -> list[Character]: ...
    def delete_character(self, character_id: str) -> None: ...
    def save_character_relation(self, relation: CharacterRelation) -> None: ...
    def get_character_relation(self, relation_id: str) -> CharacterRelation: ...
    def list_character_relations(self, *, book_id: str) -> list[CharacterRelation]: ...
    def delete_character_relation(self, relation_id: str) -> None: ...
