from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Protocol

from book_loop.domain.models import (
    Assertion,
    AssertionStatus,
    BookState,
    CanonicalFact,
    Conflict,
    DocumentChunk,
    Evidence,
    ExtractedAssertion,
    ReviewDecision,
    SceneReview,
    SourceDocument,
)


class LLMProvider(Protocol):
    def generate(self, *, system_prompt: str, user_prompt: str) -> str: ...


class EmbeddingProvider(Protocol):
    def embed(self, *, text: str) -> Sequence[float]: ...


class Writer(Protocol):
    def write(self, *, context: str) -> str: ...


class Reviewer(Protocol):
    def review(self, *, context: str, draft: str) -> SceneReview: ...


class Corrector(Protocol):
    def correct(self, *, context: str, draft: str, review: SceneReview) -> str: ...


class Summarizer(Protocol):
    def summarize(self, *, context: str, chapter: str) -> str: ...


class BookRepository(Protocol):
    def save(self, book: BookState) -> None: ...
    def get(self, book_id: str) -> BookState: ...
    def save_chapter_version(self, book_id: str, chapter_number: int, version: int, draft: str) -> None: ...
    def get_chapter_version(self, book_id: str, chapter_number: int, version: int) -> str: ...
    def save_review(self, book_id: str, chapter_number: int, version: int, review: SceneReview) -> None: ...


class AssertionExtractor(Protocol):
    def extract(self, *, chunk: DocumentChunk) -> list[ExtractedAssertion]: ...


class CanonicalKnowledgeRetriever(Protocol):
    def retrieve(self, facts: Iterable[CanonicalFact], *, query: str) -> list[CanonicalFact]: ...


class KnowledgeRepository(Protocol):
    def find_source_by_hash(self, *, book_id: str, content_hash: str) -> SourceDocument | None: ...
    def save_source(self, source: SourceDocument) -> None: ...
    def save_chunk(self, chunk: DocumentChunk) -> None: ...
    def save_assertion(self, assertion: Assertion) -> None: ...
    def save_evidence(self, evidence: Evidence) -> None: ...
    def list_assertions(self, *, book_id: str) -> list[Assertion]: ...
    def save_conflict(self, conflict: Conflict) -> None: ...
    def list_conflicts(self, *, book_id: str) -> list[Conflict]: ...
    def resolve_conflict(self, left_assertion_id: str, right_assertion_id: str, resolution_assertion_id: str) -> None: ...
    def save_review_decision(self, decision: ReviewDecision) -> None: ...
    def next_canonical_version(self, *, book_id: str, subject: str, predicate: str) -> int: ...
    def deactivate_canonical_facts(self, *, book_id: str, subject: str, predicate: str) -> None: ...
    def save_canonical_fact(self, fact: CanonicalFact) -> None: ...
    def list_active_canonical_facts(self, *, book_id: str) -> list[CanonicalFact]: ...
    def set_assertion_status(self, assertion_id: str, status: AssertionStatus) -> None: ...
