import type { BackendAssertion, BackendBook, BackendCanonicalFact, BackendConflict, BackendIngestionResult, BackendSceneReview, BackendUser, BackendWorkflowRun } from "@/types/api";
import { API_BASE_URL } from "@/services/config";
export interface CreateBookInput { title: string; theme: string; author_idea: string; lore?: string; constraints?: string[]; }
export interface GenerateChapterResult { run: BackendWorkflowRun; }
export interface ReviewChapterResult { book: BackendBook; review: BackendSceneReview; }
export interface BackendChapterContext { authorIdea: string; theme: string; lore: string; globalOutline: import("@/types/api").BackendOutline | null; constraints: string[]; previousSummaries: string; currentObjective: string; formattedContext: string; }
export class RealApiError extends Error { status: number | null; constructor(message: string, status: number | null = null) { super(message); this.name = "RealApiError"; this.status = status; } }
const RETRYABLE_STATUS = new Set([408, 429, 500, 502, 503, 504]); const MAX_RETRIES = 2; const REQUEST_TIMEOUT_MS = 30_000;
async function parseResponse(response: Response): Promise<unknown> { const text = await response.text(); if (!text) return null; try { return JSON.parse(text) as unknown; } catch { return text; } }
function errorMessage(payload: unknown, fallback: string): string { if (typeof payload === "object" && payload !== null && "detail" in payload) { const detail = (payload as { detail?: unknown }).detail; if (typeof detail === "string") return detail; } return fallback; }
function unwrapUser(payload: unknown): BackendUser { if (typeof payload === "object" && payload !== null && "user" in payload) return (payload as { user: BackendUser }).user; return payload as BackendUser; }
export class RealApiClient {
  private async request<T>(path: string, options: RequestInit = {}): Promise<T> { const method = (options.method || "GET").toUpperCase(); const canRetry = method === "GET"; let attempt = 0; while (true) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS); try { const response = await fetch(`${API_BASE_URL}${path}`, { ...options, credentials: "include", signal: controller.signal, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const payload = await parseResponse(response); if (response.ok) return payload as T; if (canRetry && attempt < MAX_RETRIES && RETRYABLE_STATUS.has(response.status)) { attempt += 1; continue; } throw new RealApiError(errorMessage(payload, `Request failed with status ${response.status}`), response.status); } catch (error) { if (error instanceof RealApiError) throw error; if (canRetry && attempt < MAX_RETRIES) { attempt += 1; continue; } throw new RealApiError(error instanceof DOMException && error.name === "AbortError" ? "La requête a expiré." : "Impossible de joindre l'API."); } finally { clearTimeout(timeout); } } }
  async getCurrentUser(): Promise<BackendUser | null> { try { return unwrapUser(await this.request<unknown>("/api/auth/me")); } catch (error) { if (error instanceof RealApiError && error.status === 401) return null; throw error; } }
  async login(email: string, password: string): Promise<BackendUser> { return unwrapUser(await this.request<unknown>("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) })); }
  async register(email: string, password: string, name: string): Promise<BackendUser> { return unwrapUser(await this.request<unknown>("/api/auth/register", { method: "POST", body: JSON.stringify({ email, password, name }) })); }
  async logout(): Promise<void> { await this.request("/api/auth/logout", { method: "POST" }); }
  listBooks(): Promise<BackendBook[]> { return this.request("/api/books"); } getBook(id: string): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}`); }
  createBook(input: CreateBookInput): Promise<BackendBook> { return this.request("/api/books", { method: "POST", body: JSON.stringify(input) }); }
  updateBook(id: string, updates: Record<string, unknown>): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(updates) }); }
  generateOutline(id: string): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}/outline/generate`, { method: "POST" }); } approveOutline(id: string): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}/outline/approve`, { method: "POST" }); }
  addChapter(id: string, n: number): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}/chapters`, { method: "POST", body: JSON.stringify({ chapter_number: n }) }); }
  generateChapter(id: string, n: number): Promise<GenerateChapterResult> { return this.request(`/api/books/${encodeURIComponent(id)}/chapters/${n}/generate`, { method: "POST" }); }
  getChapterWorkflowRun(id: string, n: number, runId: string): Promise<BackendWorkflowRun> { return this.request<{ run: BackendWorkflowRun }>(`/api/books/${encodeURIComponent(id)}/chapters/${n}/workflow-runs/${encodeURIComponent(runId)}`).then((r) => r.run); }
  getLatestChapterWorkflowRun(id: string, n: number): Promise<BackendWorkflowRun | null> { return this.request<{ run: BackendWorkflowRun | null }>(`/api/books/${encodeURIComponent(id)}/chapters/${n}/workflow-runs/latest`).then((r) => r.run); }
  reviewChapter(id: string, n: number, v?: number, draft?: string): Promise<ReviewChapterResult> { return this.request(`/api/books/${encodeURIComponent(id)}/chapters/${n}/review`, { method: "POST", body: JSON.stringify({ versionNumber: v, draftText: draft }) }); }
  approveChapter(id: string, n: number): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}/chapters/${n}/approve`, { method: "POST" }); } rejectChapter(id: string, n: number): Promise<BackendBook> { return this.request(`/api/books/${encodeURIComponent(id)}/chapters/${n}/reject`, { method: "POST" }); }
  getChapterContext(id: string, n: number): Promise<BackendChapterContext> { return this.request(`/api/books/${encodeURIComponent(id)}/chapters/${n}/context`); }
  ingestDocument(id: string, name: string, content: string, sourceType = "markdown"): Promise<BackendIngestionResult> { return this.request(`/api/books/${encodeURIComponent(id)}/documents/ingest`, { method: "POST", body: JSON.stringify({ name, content, sourceType }) }); }
  async listAssertions(id: string): Promise<BackendAssertion[]> { return (await this.request<{ assertions: BackendAssertion[] }>(`/api/books/${encodeURIComponent(id)}/assertions`)).assertions; }
  async listConflicts(id: string): Promise<BackendConflict[]> { return (await this.request<{ conflicts: BackendConflict[] }>(`/api/books/${encodeURIComponent(id)}/conflicts`)).conflicts; }
  async listCanonicalFacts(id: string): Promise<BackendCanonicalFact[]> { return (await this.request<{ facts: BackendCanonicalFact[] }>(`/api/books/${encodeURIComponent(id)}/canonical-facts`)).facts; }
  reviewAssertion(id: string, assertionId: string, decision: "accept" | "reject" | "defer", rationale = ""): Promise<void> { return this.request(`/api/books/${encodeURIComponent(id)}/assertions/${encodeURIComponent(assertionId)}/review`, { method: "POST", body: JSON.stringify({ decision, rationale }) }); }
}
export const realApiClient = new RealApiClient();
